---
# Name your file secrets.yml

development:
  DB_FILENAME: db/local/dev.db
  SPOTIFY_CLIENT_ID: create_spotify_client_id
  SPOTIFY_CLIENT_SECRET: create_spotify_client_secret
  GENIUS_CLIENT_ACCESS_TOKEN: create_genius_client_access_token
  SESSION_SECRET: <some secret>

test:
  DB_FILENAME: db/local/test.db
  SPOTIFY_CLIENT_ID: create_spotify_client_id
  SPOTIFY_CLIENT_SECRET: create_spotify_client_secret
  GENIUS_CLIENT_ACCESS_TOKEN: create_genius_client_access_token
  SESSION_SECRET: <some secret>

production:
  SPOTIFY_CLIENT_ID: create_spotify_client_id
  SPOTIFY_CLIENT_SECRET: create_spotify_client_secret
  GENIUS_CLIENT_ACCESS_TOKEN: create_genius_client_access_token
  SESSION_SECRET: <some secret>